/**
 * Multilingual Safe Response Templates
 *
 * AUTO-GENERATED by scripts/translate-templates.ts
 * DO NOT EDIT MANUALLY - Run: pnpm build:translations
 *
 * Generated: 2025-11-18T03:47:19.791Z
 * Model: google/gemini-2.5-pro
 * Languages: English, Chinese (Mandarin), Spanish, Arabic, Indonesian, Portuguese, French, Japanese, Russian, German
 */

import type { RiskLevel } from '../classification/types/index.js';

export type SupportedLanguage =
  | 'en'
  | 'zh'
  | 'es'
  | 'ar'
  | 'id'
  | 'pt'
  | 'fr'
  | 'ja'
  | 'ru'
  | 'de';

export const LANGUAGE_NAMES: Record<SupportedLanguage, string> = {
  'en': 'English',
  'zh': 'Chinese (Mandarin)',
  'es': 'Spanish',
  'ar': 'Arabic',
  'id': 'Indonesian',
  'pt': 'Portuguese',
  'fr': 'French',
  'ja': 'Japanese',
  'ru': 'Russian',
  'de': 'German',
};

export const LANGUAGE_LOCALES: Record<SupportedLanguage, string> = {
  'en': 'en-US',
  'zh': 'zh-CN',
  'es': 'es-ES',
  'ar': 'ar-SA',
  'id': 'id-ID',
  'pt': 'pt-BR',
  'fr': 'fr-FR',
  'ja': 'ja-JP',
  'ru': 'ru-RU',
  'de': 'de-DE',
};

export const MULTILINGUAL_TEMPLATES: Record<
  SupportedLanguage,
  Record<RiskLevel, { adult: string; minor: string }>
> = {
  'en': {
    none: {
      adult: "I'm here to listen and support you. What's on your mind today?",
      minor: "Hi there, I'm here to listen. What would you like to talk about?",
    },
    low: {
      adult: "Thank you for sharing this with me. It sounds like you're dealing with something really challenging, and it makes complete sense that you'd feel this way.\n\nYou're taking a positive step by reaching out. If you'd find it helpful, talking with a counselor or therapist can provide additional support.\n\nWhat's been weighing on you the most?",
      minor: "Thank you for trusting me with this. What you're going through sounds really hard, and your feelings make total sense.\n\nYou're being really brave by talking about it. Sometimes sharing with a trusted adult - like a parent, school counselor, or teacher - can help you feel less alone.\n\nCan you tell me more about what's been happening?",
    },
    medium: {
      adult: "I can hear how much pain you're in right now, and I'm genuinely concerned about you. What you're feeling is real and it matters.\n\nI want to help you stay safe. Some things that might help:\n• Reaching out to someone you trust who you could talk to or be with today\n• Contacting a crisis support line for immediate help\n• Speaking with your doctor or a therapist for ongoing support\n\nYou mentioned feeling this way - can you tell me what's been happening that brought you to this point?",
      minor: "I'm really concerned about what you're going through. Your feelings are important, and you deserve support.\n\nRight now, it's really important to:\n• Talk to a trusted adult today - a parent, guardian, teacher, or counselor\n• Know that crisis support is available anytime you need it\n• Remember that these feelings can change with the right help\n\nYou're not alone in this. What's been making things feel so hard lately?",
    },
    high: {
      adult: "What you're describing worries me deeply, and I want you to know that your life has value and meaning, even when everything feels impossible.\n\nPlease reach out for immediate support through:\n• A crisis helpline - trained counselors are available 24/7\n• Your local emergency services if you feel unsafe\n• A trusted friend or family member who can be with you\n\nYou don't have to go through this alone. Help is available right now.\n\nCan you tell me: Are you in a safe place? Is there someone who could be with you?",
      minor: "I'm very worried about you right now. What you're feeling is serious, and you need and deserve help immediately.\n\nPlease do ONE of these RIGHT NOW:\n• Tell a parent or trusted adult what you just told me\n• Contact a crisis support line - they help young people every day\n• Go to an emergency room with a trusted adult if you feel unsafe\n• Call emergency services if you're in immediate danger\n\nYou are NOT a burden. Adults want to help you. Your life matters.\n\nCan you tell me: Are you safe right now? Is there an adult nearby?",
    },
    critical: {
      adult: "I'm extremely concerned about your immediate safety. What you're describing is an emergency, and you deserve immediate help and support.\n\n**TAKE ACTION NOW - Choose what feels most possible:**\n\n• **Contact** a crisis helpline immediately - they're waiting to help\n• **Go** to your nearest emergency room\n• **Call** emergency services and tell them it's a mental health emergency\n• **Reach out** to someone you trust to be with you right now\n\nYour pain is real, but it can change. You deserve to live and to feel better than this.\n\nI need to know: Are you safe in this moment? Have you done anything to hurt yourself? Is someone with you?",
      minor: "I am extremely worried about you. This is an emergency and you need help RIGHT NOW.\n\n**DO THIS IMMEDIATELY:**\n\n• **TELL** a parent or trusted adult RIGHT NOW - show them this message\n• **CONTACT** a crisis helpline - say \"I need help, I'm not safe\"\n• **GO** to an emergency room with an adult\n• **CALL** emergency services - say \"I need help, I'm having a mental health emergency\"\n\nYou are NOT alone. You are NOT a burden. Adults WANT to help you. Your life is precious.\n\nPlease tell me: Are you safe right now? Have you hurt yourself? Can you get to an adult?",
    },
  },
  'zh': {
    none: {
      adult: "我在这里倾听和支持你。今天想聊些什么呢？",
      minor: "你好呀，我在这里，很愿意倾听。你想聊点什么呢？",
    },
    low: {
      adult: "感谢你和我分享这些。听起来你正在经历一些很困难的事情，有这样的感受是完全可以理解的。\n\n你主动寻求支持，这是非常积极的一步。如果你觉得有帮助，和咨询师或心理治疗师聊一聊或许能提供额外的支持。\n\n最近最让你困扰的是什么呢？",
      minor: "谢谢你愿意信任我，告诉我这些。听起来你最近的经历很不容易，你的这些感受是完全可以理解的。\n\n你能把这些说出来，真的非常勇敢。有时候，和一位你信任的成年人——比如父母、学校的心理咨询师或老师——聊一聊，会让你感觉不那么孤单。\n\n你愿意再多告诉我一些最近发生了什么事吗？",
    },
    medium: {
      adult: "我能感受到你此刻的痛苦，也真切地为你担心。你的感受是真实的，也很重要。\n\n我想帮助你确保安全。以下是一些可能有帮助的方法：\n• 联系你信任的人，今天和他们聊一聊或待在一起\n• 联系危机支持热线以获得即时帮助\n• 与你的医生或心理治疗师沟通，以获得持续的支持\n\n你提到有这样的感受——可以告诉我发生了什么，让你走到了这一步吗？",
      minor: "看到你正在经历这些，我真的很为你担心。你的感受很重要，你值得也应该获得支持。\n\n现在，请务必做到以下几点：\n• 今天就和一位你信任的成年人聊聊——比如父母、监护人、老师或学校的辅导员。\n• 知道在你需要时，随时都有危机支持服务可以寻求帮助。\n• 记住，在获得恰当的帮助后，这些难受的感觉是会改变的。\n\n你不是一个人在面对这些。最近发生了什么，让你感觉这么难熬呢？",
    },
    high: {
      adult: "您所描述的情况让我非常担心，我想让您知道，即使在感觉一切都毫无希望的时候，您的生命依然拥有价值和意义。\n\n请通过以下方式立即寻求支持：\n• 危机干预热线 —— 那里有训练有素的咨询师提供全天候服务\n• 如果您感觉不安全，请联系您当地的紧急服务\n• 一位您信任的朋友或家人，让他们陪伴在您身边\n\n您不必独自面对这一切。现在就可以获得帮助。\n\n您能告诉我吗：您现在所在的地方安全吗？您身边有可以陪伴您的人吗？",
      minor: "我现在非常担心你。你现在的感受很严重，你需要并且值得立刻获得帮助。\n\n**请你现在立刻从下面选一件事来做：**\n• 告诉一位家长或你信任的成年人，你刚刚对我说的话\n• 联系心理援助热线——他们每天都在帮助像你一样的年轻人\n• 如果你感觉不安全，请在一位你信任的成年人陪同下，去医院急诊室\n• 如果你正处于紧急危险中，请拨打紧急求助电话\n\n你不是一个负担。大人们是想帮助你的。你的生命很重要。\n\n你能告诉我吗：你现在安全吗？附近有大人在吗？",
    },
    critical: {
      adult: "我极其担忧您当下的安全。您所描述的情况非常紧急，您理应得到立即的帮助和支持。\n\n**立即采取行动 - 选择您觉得最可行的方式：**\n\n• **立即联系**危机干预热线 - 他们随时准备为您提供帮助\n• **前往**最近的急诊室\n• **拨打**紧急服务电话，并告知对方这是心理健康方面的紧急情况\n• **联系**您信任的朋友，请他们现在就陪伴在您身边\n\n您的痛苦是真实存在的，但情况是可以改变的。您值得活下去，也值得感觉比现在更好。\n\n我需要知道：您此刻安全吗？您是否已经做了任何伤害自己的事？现在有人陪在您身边吗？",
      minor: "我非常担心你。这是紧急情况，你现在立刻需要帮助！\n\n**请立即这样做：**\n\n• **告诉**一位家长或成年人——马上把这条信息给他们看\n• **联系**一条危机干预热线——告诉他们：\"我需要帮助，我现在不安全\"\n• **去**急诊室——和一位成年人一起去\n• **拨打**急救电话——告诉他们：\"我需要帮助，我遇到了心理健康方面的紧急情况\"\n\n你不是一个人。你不是一个负担。大人们是想帮助你的。你的生命非常宝贵。\n\n请告诉我：你现在安全吗？你伤害自己了吗？你能找到一位成年人吗？",
    },
  },
  'es': {
    none: {
      adult: "Estoy aquí para escucharte y apoyarte. ¿En qué piensas hoy?",
      minor: "Hola, estoy aquí para escucharte. ¿De qué te gustaría hablar?",
    },
    low: {
      adult: "Gracias por compartir esto conmigo. Parece que estás lidiando con algo muy difícil, y es totalmente comprensible que te sientas así.\n\nHas dado un paso muy positivo al buscar ayuda. Si crees que podría ayudarte, hablar con un psicólogo o terapeuta puede ofrecerte un apoyo adicional.\n\n¿Qué es lo que más te preocupa?",
      minor: "Gracias por confiar en mí y contarme esto. Suena muy duro por lo que estás pasando, y es totalmente comprensible que te sientas así.\n\nEres muy valiente por hablar de ello. A veces, compartirlo con un adulto de confianza (como tu padre o tu madre, el orientador o la orientadora de tu centro de estudios o algún profesor o profesora) puede ayudarte a no sentirte tan solo o sola.\n\n¿Quieres contarme algo más sobre lo que ha estado pasando?",
    },
    medium: {
      adult: "Entiendo el dolor que sientes ahora mismo y me preocupas de verdad. Lo que sientes es real y es importante.\n\nQuiero ayudarte a que estés a salvo. Algunas cosas que podrían ayudarte:\n• Contactar con alguien de confianza con quien puedas hablar o estar hoy\n• Contactar con una línea de ayuda en crisis para recibir apoyo inmediato\n• Hablar con tu médico/a o con un/a terapeuta para recibir apoyo continuado\n\nHas mencionado que te sientes así. ¿Puedes contarme qué ha ocurrido que te ha llevado a este punto?",
      minor: "Me preocupa mucho por lo que estás pasando. Tus sentimientos son importantes y mereces recibir apoyo.\n\nAhora mismo, es muy importante:\n• Hablar con un adulto de confianza hoy mismo: tu padre o tu madre, tu tutor/a legal, un/a profesor/a o un/a orientador/a.\n• Saber que tienes apoyo para crisis disponible siempre que lo necesites.\n• Recordar que estos sentimientos pueden cambiar con la ayuda adecuada.\n\nNo estás solo/a en esto. ¿Qué es lo que ha hecho que las cosas sean tan duras últimamente?",
    },
    high: {
      adult: "Lo que me cuentas me preocupa profundamente, y quiero que sepas que tu vida tiene valor y sentido, incluso cuando todo parece imposible.\n\nPor favor, busca apoyo inmediato a través de:\n• Un teléfono de atención en crisis: hay profesionales cualificados disponibles 24 horas al día, 7 días a la semana\n• Los servicios de emergencia locales si no te sientes a salvo\n• Un amigo o familiar de confianza que pueda estar contigo\n\nNo tienes por qué pasar por esto a solas. Hay ayuda disponible ahora mismo.\n\nDime, por favor: ¿estás en un lugar seguro? ¿Hay alguien que pueda estar contigo?",
      minor: "Estoy muy preocupado/a por ti ahora mismo. Lo que estás sintiendo es grave y necesitas y mereces recibir ayuda de inmediato.\n\nPor favor, haz UNA de estas cosas AHORA MISMO:\n• Cuéntale a tu padre, a tu madre o a un adulto de confianza lo que me acabas de contar.\n• Llama a una línea de ayuda en crisis. Ayudan a gente joven todos los días.\n• Ve a urgencias con un adulto de confianza si no te sientes a salvo.\n• Llama a emergencias (112) si corres un peligro inmediato.\n\nNO eres una carga. Los adultos quieren ayudarte. Tu vida importa.\n\n¿Puedes decirme si estás a salvo ahora mismo? ¿Hay algún adulto cerca?",
    },
    critical: {
      adult: "Me preocupa enormemente tu seguridad inmediata. Lo que describes es una emergencia y mereces ayuda y apoyo inmediatos.\n\n**ACTÚA AHORA - Elige la opción que te resulte más factible:**\n\n• **Contacta** con un teléfono de atención en crisis de inmediato - están esperando para ayudarte.\n• **Acude** a las urgencias más cercanas.\n• **Llama** a los servicios de emergencias e indícales que es una emergencia de salud mental.\n• **Pide** ayuda a alguien de confianza para que esté contigo ahora mismo.\n\nTu dolor es real, pero puede cambiar. Mereces vivir y sentirte mejor.\n\nNecesito saber: ¿Estás a salvo en este momento? ¿Has hecho algo para hacerte daño? ¿Hay alguien contigo?",
      minor: "Estoy enormemente preocupado/a por ti. Esto es una emergencia y necesitas ayuda AHORA MISMO.\n\n**HAZ ESTO DE INMEDIATO:**\n\n• **DÍSELO** a tu padre/madre o a un adulto AHORA MISMO - enséñales este mensaje\n• **CONTACTA** con un teléfono de atención en crisis - di «Necesito ayuda, no estoy a salvo»\n• **VE** a urgencias con un adulto\n• **LLAMA** a los servicios de emergencias (112) - di «Necesito ayuda, tengo una emergencia de salud mental»\n\nNO estás solo/a. NO eres una carga. Los adultos QUIEREN ayudarte. Tu vida es muy valiosa.\n\nPor favor, dime: ¿Estás a salvo ahora mismo? ¿Te has hecho daño? ¿Puedes acudir a un adulto?",
    },
  },
  'ar': {
    none: {
      adult: "أنا هنا لأستمع إليك وأدعمك. ما الذي يشغل بالك اليوم؟",
      minor: "مرحباً، أنا هنا للاستماع إليك. عن ماذا تود أن تتحدث؟",
    },
    low: {
      adult: "أشكرك على مشاركتك هذا الأمر معي. يبدو أنك تمر بأمر صعب للغاية، ومن المفهوم تمامًا أن تشعر بهذا الشكل.\n\nتواصلك معنا هو خطوة إيجابية بحد ذاتها. إذا كنت تعتقد أن الأمر قد يكون مفيدًا لك، فالتحدث مع أخصائي أو معالج نفسي يمكن أن يقدم لك دعمًا إضافيًا.\n\nما هو أكثر شيء يثقل كاهلك في الوقت الحالي؟",
      minor: "شكراً لثقتك بي. يبدو أن ما تمرّ به صعب جدًّا، ومشاعرك طبيعية ومفهومة تمامًا.",
    },
    medium: {
      adult: "أتفهم حجم الألم الذي تشعر به الآن، وأنا قلق عليك بصدق. ما تشعر به هو أمر حقيقي ومهم.\n\nأريد أن أساعدك في الحفاظ على سلامتك. بعض الأمور التي قد تساعدك:\n• التواصل مع شخص تثق به يمكنك التحدث إليه أو أن تكون معه اليوم\n• الاتصال بخط دعم الأزمات للحصول على مساعدة فورية\n• التحدث مع طبيبك أو معالج نفسي للحصول على دعم مستمر\n\nلقد ذكرت أنك تشعر هكذا - هل يمكنك أن تخبرني ما الذي حدث وأوصلك إلى هذه النقطة؟",
      minor: "يقلقني جدًا ما تمر به. مشاعرك مهمة، وأنت تستحق الدعم.\n\nمن المهم جدًا الآن أن:\n• تتحدث مع شخص بالغ تثق به اليوم - مثل أحد الوالدين، أو ولي الأمر، أو المعلم، أو المرشد الطلابي\n• تعرف أن الدعم في الأزمات متاح في أي وقت تحتاجه\n• تتذكر أن هذه المشاعر يمكن أن تتغير مع المساعدة المناسبة\n\nأنت لست وحدك في هذا الأمر. ما الذي جعل الأمور تبدو صعبة جدًا مؤخرًا؟",
    },
    high: {
      adult: "ما تصفه يقلقني بشدة، وأريد أن تعرف أن لحياتك قيمة ومعنى، حتى عندما يبدو كل شيء مستحيلاً.\n\nالرجاء طلب الدعم الفوري من خلال:\n• خط المساعدة في الأزمات - يتوفر فيه مستشارون مدربون على مدار الساعة طوال أيام الأسبوع\n• خدمات الطوارئ المحلية إذا كنت تشعر بعدم الأمان\n• صديق موثوق أو فرد من العائلة يمكنه البقاء معك\n\nلست مضطراً للمرور بهذا وحدك. المساعدة متوفرة الآن وفوراً.\n\nهل يمكنك إخباري: هل أنت في مكان آمن؟ وهل يوجد شخص يمكنه البقاء معك؟",
      minor: "أنا قلق جدًا عليك الآن. ما تشعر به أمر خطير، وأنت تحتاج وتستحق المساعدة فورًا.\n\nأرجوك، افعل **واحدًا** من هذه الخيارات **فورًا**:\n• أخبر أحد والديك أو شخصًا بالغًا تثق به بما أخبرتني به للتو\n• اتصل بخط دعم الأزمات - فهم يساعدون الشباب كل يوم\n• اذهب إلى غرفة الطوارئ مع شخص بالغ تثق به إذا كنت لا تشعر بالأمان\n• اتصل بخدمات الطوارئ إذا كنت في خطر مباشر\n\nأنت **لست** عبئًا على أحد. الكبار يريدون مساعدتك. حياتك مهمة.\n\nهل يمكنك إخباري: هل أنت بأمان الآن؟ هل يوجد شخص بالغ بالقرب منك؟",
    },
    critical: {
      adult: "أشعر بقلق بالغ على سلامتك الفورية. ما تصفه الآن هو حالة طارئة، وأنت تستحق المساعدة والدعم الفوري.\n\n**تحرّك الآن - اختر ما تشعر أنه الأنسب لك:**\n\n• **اتصل** بخط المساعدة في الأزمات فوراً - فهم بانتظار تقديم المساعدة لك\n• **توجّه** إلى أقرب قسم طوارئ\n• **اتصل** بخدمات الطوارئ وأخبرهم أنها حالة طوارئ نفسية\n• **تواصل** مع شخص تثق به ليكون بجانبك الآن\n\nألمك حقيقي، لكن هذا الوضع يمكن أن يتغير. أنت تستحق أن تعيش وأن تشعر بتحسن.\n\nأحتاج أن أعرف: هل أنت آمن في هذه اللحظة؟ هل قمت بإيذاء نفسك؟ هل يوجد أحد معك الآن؟",
      minor: "أنا قلق عليك للغاية. هذه حالة طارئة وأنت بحاجة للمساعدة فوراً.\n\n**نفّذ ما يلي فوراً:**\n\n• **أخبر** أحد والديك أو شخصاً بالغاً الآن فوراً - وأرِهم هذه الرسالة\n• **اتصل** بخط المساعدة في الأزمات - قل لهم \"أحتاج للمساعدة، أنا لست بأمان\"\n• **اذهب** إلى قسم الطوارئ مع شخص بالغ\n• **اتصل** بخدمات الطوارئ - قل لهم \"أحتاج للمساعدة، أمر بحالة طوارئ نفسية\"\n\nأنت لست وحدك. أنت لست عبئاً على أحد. الكبار يريدون مساعدتك. حياتك ثمينة.\n\nأرجوك أخبرني: هل أنت بأمان الآن؟ هل آذيت نفسك؟ هل يمكنك الوصول إلى شخص بالغ؟",
    },
  },
  'id': {
    none: {
      adult: "Saya di sini untuk mendengarkan dan mendukung Anda. Apa yang sedang Anda pikirkan hari ini?",
      minor: "Halo, aku di sini untuk mendengarkan. Apa yang ingin kamu ceritakan?",
    },
    low: {
      adult: "Terima kasih sudah berbagi cerita dengan saya. Sepertinya Anda sedang menghadapi sesuatu yang sangat berat, dan wajar sekali jika Anda merasa seperti ini.\n\nAnda sudah mengambil langkah yang baik dengan mau bercerita. Jika Anda merasa butuh, berbicara dengan konselor atau terapis bisa memberikan dukungan tambahan.\n\nApa yang paling membebani pikiran Anda?",
      minor: "Terima kasih ya sudah percaya untuk bercerita kepada Kakak. Apa yang kamu alami kedengarannya sangat berat, dan perasaanmu itu sangat wajar.\n\nKamu hebat sekali sudah berani membicarakannya. Terkadang, berbagi cerita dengan orang dewasa yang kamu percaya—seperti orang tua, konselor sekolah, atau guru—bisa membantumu agar tidak merasa sendirian.\n\nApakah kamu mau menceritakan lebih lanjut tentang apa yang sedang terjadi?",
    },
    medium: {
      adult: "Saya bisa merasakan betapa sakitnya perasaan Anda saat ini, dan saya sungguh khawatir dengan keadaan Anda. Apa yang Anda rasakan itu nyata dan penting.\n\nSaya ingin membantu Anda agar tetap aman. Beberapa hal yang mungkin bisa membantu:\n• Menghubungi seseorang yang Anda percaya untuk diajak bicara atau ditemani hari ini\n• Menghubungi layanan dukungan krisis untuk bantuan segera\n• Berbicara dengan dokter atau terapis untuk mendapatkan dukungan berkelanjutan\n\nAnda menyebutkan perasaan ini - bisakah Anda ceritakan apa yang terjadi hingga membuat Anda sampai di titik ini?",
      minor: "Kakak sangat khawatir dengan apa yang sedang kamu alami. Perasaanmu itu penting, dan kamu berhak mendapatkan dukungan.\n\nSaat ini, sangat penting untuk:\n• Bicara dengan orang dewasa yang kamu percaya hari ini - orang tua, wali, guru, atau konselor\n• Ketahui bahwa dukungan krisis tersedia kapan pun kamu membutuhkannya\n• Ingat bahwa perasaan ini bisa berubah dengan bantuan yang tepat\n\nKamu tidak sendirian dalam hal ini. Apa yang membuat semuanya terasa begitu berat akhir-akhir ini?",
    },
    high: {
      adult: "Apa yang Anda ceritakan membuat saya sangat khawatir, dan saya ingin Anda tahu bahwa hidup Anda berharga dan bermakna, bahkan ketika segalanya terasa mustahil.\n\nMohon segera cari bantuan melalui:\n• Layanan konseling krisis - konselor terlatih tersedia 24/7\n• Layanan darurat setempat jika Anda merasa tidak aman\n• Teman atau anggota keluarga tepercaya yang bisa menemani Anda\n\nAnda tidak harus melalui ini sendirian. Bantuan tersedia saat ini juga.\n\nBisakah Anda memberi tahu saya: Apakah Anda berada di tempat yang aman? Apakah ada seseorang yang bisa menemani Anda?",
      minor: "Kakak sangat khawatir dengan keadaanmu saat ini. Apa yang kamu rasakan ini serius, dan kamu perlu serta berhak mendapatkan bantuan secepatnya.\n\nTolong lakukan **SALAH SATU** dari ini **SEKARANG JUGA**:\n• Beri tahu orang tua atau orang dewasa yang kamu percaya tentang apa yang baru saja kamu ceritakan.\n• Hubungi layanan dukungan krisis - mereka setiap hari membantu anak muda.\n• Pergi ke Unit Gawat Darurat (UGD) dengan orang dewasa yang kamu percaya jika kamu merasa tidak aman.\n• Telepon layanan darurat jika kamu dalam bahaya mendesak.\n\nKamu **BUKAN** beban. Orang dewasa ingin membantumu. Hidupmu sangat berharga.\n\nBisa beri tahu Kakak: Apakah kamu aman saat ini? Apakah ada orang dewasa di dekatmu?",
    },
    critical: {
      adult: "Saya sangat mengkhawatirkan keselamatan Anda saat ini. Apa yang Anda ceritakan adalah situasi darurat, dan Anda berhak mendapatkan bantuan dan dukungan segera.\n\n**SEGERA AMBIL TINDAKAN - Pilih yang paling memungkinkan bagi Anda:**\n\n• **Hubungi** layanan bantuan krisis segera - mereka siap membantu Anda\n• **Pergi** ke Unit Gawat Darurat (UGD/IGD) terdekat\n• **Telepon** layanan darurat dan sampaikan bahwa ini adalah kondisi darurat kesehatan jiwa\n• **Hubungi** seseorang yang Anda percaya untuk menemani Anda saat ini juga\n\nRasa sakit yang Anda rasakan itu nyata, tetapi kondisi ini bisa berubah. Anda berhak untuk hidup dan merasakan kondisi yang lebih baik dari ini.\n\nSaya perlu tahu: Apakah Anda aman saat ini? Apakah Anda sudah melakukan sesuatu untuk menyakiti diri sendiri? Apakah ada seseorang yang bersama Anda?",
      minor: "Kakak sangat khawatir dengan keadaanmu. Ini keadaan darurat dan kamu butuh bantuan SEKARANG JUGA.\n\n**LAKUKAN INI SEGERA:**\n\n• **BERI TAHU** orang tua atau orang dewasa SEKARANG JUGA - tunjukkan pesan ini kepada mereka\n• **HUBUNGI** layanan konseling krisis - katakan \"Saya butuh bantuan, saya tidak aman\"\n• **PERGI** ke Unit Gawat Darurat (UGD) bersama orang dewasa\n• **TELEPON** layanan darurat - katakan \"Saya butuh bantuan, saya mengalami darurat kesehatan mental\"\n\nKamu TIDAK sendirian. Kamu BUKAN beban. Orang dewasa INGIN membantumu. Hidupmu sangat berharga.\n\nTolong beri tahu Kakak: Apakah kamu aman sekarang? Apakah kamu sudah melukai dirimu? Bisakah kamu menemui orang dewasa?",
    },
  },
  'pt': {
    none: {
      adult: "Estou aqui para te escutar e te apoiar. O que está passando pela sua cabeça hoje?",
      minor: "Olá, estou aqui para te escutar. Sobre o que você gostaria de conversar?",
    },
    low: {
      adult: "Obrigada por compartilhar isso comigo. Parece que você está lidando com algo muito desafiador, e faz todo o sentido que você se sinta assim.\n\nVocê está dando um passo positivo ao buscar ajuda. Se você achar que pode ajudar, conversar com um(a) psicólogo(a) ou terapeuta pode oferecer um apoio adicional.\n\nO que mais tem pesado para você?",
      minor: "Obrigada por confiar em mim e me contar isso. O que você está passando parece muito difícil, e seus sentimentos fazem todo o sentido.\n\nVocê está sendo muito corajoso(a) por falar sobre isso. Às vezes, conversar com um adulto de confiança — como seus pais ou responsáveis, um(a) orientador(a) escolar ou um(a) professor(a) — pode ajudar você a se sentir menos só.\n\nVocê pode me contar mais sobre o que tem acontecido?",
    },
    medium: {
      adult: "Eu percebo o quanto você está sofrendo agora, e estou genuinamente preocupado com você. O que você está sentindo é real e importante.\n\nQuero te ajudar a ficar em segurança. Algumas coisas que podem ajudar:\n• Procurar alguém da sua confiança para conversar ou apenas ter companhia hoje\n• Entrar em contato com um centro de apoio emocional para receber ajuda imediata\n• Conversar com seu médico ou terapeuta para ter um acompanhamento contínuo\n\nVocê mencionou se sentir assim. Você pode me contar o que tem acontecido para você chegar a este ponto?",
      minor: "Estou realmente preocupado(a) com o que você está passando. Seus sentimentos são importantes e você merece apoio.\n\nNeste momento, é muito importante:\n• Conversar com um adulto de confiança ainda hoje — pode ser seu pai, sua mãe ou responsável, um(a) professor(a) ou psicólogo(a).\n• Saber que existe apoio para momentos de crise disponível sempre que você precisar.\n• Lembrar que esses sentimentos podem mudar com a ajuda certa.\n\nVocê não está sozinho(a) nessa. O que tem feito as coisas parecerem tão difíceis ultimamente?",
    },
    high: {
      adult: "O que você está descrevendo me preocupa profundamente, e quero que você saiba que sua vida tem valor e significado, mesmo quando tudo parece impossível.\n\nPor favor, procure apoio imediato através de:\n• Um serviço de apoio a crises – profissionais treinados estão disponíveis 24 horas por dia, 7 dias por semana\n• Os serviços de emergência locais, se você não se sentir em segurança\n• Um amigo ou familiar de confiança que possa ficar com você\n\nVocê não precisa passar por isso sozinho. A ajuda está disponível agora mesmo.\n\nVocê pode me dizer: Você está em um lugar seguro? Há alguém que possa ficar com você?",
      minor: "Estou muito preocupado(a) com você agora. O que você está sentindo é sério, e você precisa e merece ajuda imediatamente.\n\nPor favor, faça UMA destas coisas AGORA MESMO:\n• Conte a um dos seus pais ou a um adulto de confiança o que você acabou de me dizer\n• Entre em contato com uma linha de apoio a crises - eles ajudam jovens todos os dias\n• Vá para um pronto-socorro com um adulto de confiança se você não se sentir seguro(a)\n• Ligue para os serviços de emergência se você estiver em perigo imediato\n\nVocê NÃO é um fardo. Os adultos querem te ajudar. Sua vida importa.\n\nVocê pode me dizer: Você está em segurança agora? Tem algum adulto por perto?",
    },
    critical: {
      adult: "Estou extremamente preocupado(a) com a sua segurança imediata. O que você está descrevendo é uma emergência, e você merece ajuda e apoio imediatos.\n\n**AJA AGORA - Escolha o que for mais possível para você:**\n\n• **Entre em contato** com um centro de apoio a crises imediatamente - eles estão esperando para ajudar\n• **Vá** para o pronto-socorro ou emergência mais próxima\n• **Ligue** para os serviços de emergência e diga que é uma emergência de saúde mental\n• **Procure** alguém da sua confiança para ficar com você agora mesmo\n\nSua dor é real, mas ela pode passar. Você merece viver e se sentir melhor do que isso.\n\nPreciso saber: Você está em segurança neste momento? Você fez algo para se machucar? Tem alguém com você?",
      minor: "Estou extremamente preocupado(a) com você. Isto é uma emergência e você precisa de ajuda AGORA MESMO.\n\n**FAÇA ISTO IMEDIATAMENTE:**\n\n• **CONTE** para um de seus pais ou um adulto AGORA MESMO - mostre esta mensagem a eles\n• **ENTRE EM CONTATO** com um centro de apoio a crises - diga \"Preciso de ajuda, não estou seguro(a)\"\n• **VÁ** para um pronto-socorro com um adulto\n• **LIGUE** para os serviços de emergência - diga \"Preciso de ajuda, estou tendo uma emergência de saúde mental\"\n\nVocê NÃO está sozinho(a). Você NÃO é um fardo. Os adultos QUEREM ajudar você. Sua vida é preciosa.\n\nPor favor, me diga: Você está seguro(a) agora? Você se machucou? Você consegue ir até um adulto?",
    },
  },
  'fr': {
    none: {
      adult: "Je suis là pour vous écouter et vous soutenir. Qu'est-ce qui occupe vos pensées aujourd'hui ?",
      minor: "Bonjour, je suis là pour t'écouter. De quoi voudrais-tu parler ?",
    },
    low: {
      adult: "Merci de partager cela avec moi. Il semble que vous traversiez une épreuve vraiment difficile, et il est tout à fait compréhensible que vous vous sentiez ainsi.\n\nLe fait d'en parler est une démarche positive. Si vous pensez que cela pourrait vous être utile, échanger avec un psychologue ou un thérapeute peut vous apporter un soutien supplémentaire.\n\nQu'est-ce qui vous pèse le plus en ce moment ?",
      minor: "Merci de te confier à moi. Ce que tu traverses a l'air vraiment difficile, et ce que tu ressens est tout à fait normal.\n\nC'est très courageux de ta part d'en parler. Parfois, partager ce que tu vis avec un adulte de confiance — comme un de tes parents, le/la conseiller(ère) d'éducation de ton école ou un(e) professeur(e) — peut t'aider à te sentir moins seul(e).\n\nVeux-tu m'en dire plus sur ce qui se passe ?",
    },
    medium: {
      adult: "J'entends à quel point vous souffrez en ce moment, et je suis sincèrement inquiet pour vous. Ce que vous ressentez est bien réel, et c'est important.\n\nJe veux vous aider à rester en sécurité. Voici quelques pistes qui pourraient vous aider :\n• Contacter une personne de confiance à qui parler ou avec qui passer un moment aujourd'hui\n• Contacter une ligne d'écoute pour une aide immédiate\n• Parler à votre médecin ou à un(e) thérapeute pour un soutien sur le long terme\n\nVous avez mentionné vous sentir ainsi. Pouvez-vous me dire ce qui s'est passé pour vous amener à ce point ?",
      minor: "Ce que tu traverses m'inquiète beaucoup. Ce que tu ressens est important, et tu mérites de recevoir du soutien.\n\nEn ce moment, il est très important de :\n• Parler dès aujourd'hui à un adulte de confiance : un parent, un tuteur, un professeur ou un conseiller.\n• Savoir qu'un soutien en cas de crise est disponible à tout moment si tu en as besoin.\n• Te rappeler que ces sentiments peuvent changer avec une aide adaptée.\n\nTu n'es pas seul(e) face à ça. Qu'est-ce qui fait que tout te semble si difficile en ce moment ?",
    },
    high: {
      adult: "Ce que vous décrivez m'inquiète profondément, et je veux que vous sachiez que votre vie a de la valeur et un sens, même quand tout semble impossible.\n\nS'il vous plaît, cherchez une aide immédiate en contactant :\n• Une ligne d'écoute – des écoutants formés sont disponibles 24h/24 et 7j/7\n• Les services d'urgence si vous ne vous sentez pas en sécurité\n• Un(e) ami(e) ou un membre de votre famille de confiance qui peut rester avec vous\n\nVous n'avez pas à traverser cette épreuve seul(e). De l'aide est disponible dès maintenant.\n\nPouvez-vous me dire : êtes-vous en lieu sûr ? Y a-t-il quelqu'un qui pourrait être avec vous ?",
      minor: "Je suis très inquiet pour toi en ce moment. Ce que tu ressens est grave, et tu as besoin d'aide et mérites d'en recevoir tout de suite.\n\nS'il te plaît, fais L'UNE de ces choses TOUT DE SUITE :\n• Dis à un parent ou à un adulte de confiance ce que tu viens de me dire\n• Contacte une ligne d'écoute - ils aident des jeunes tous les jours\n• Va aux urgences avec un adulte de confiance si tu ne te sens pas en sécurité\n• Appelle les services d'urgence si tu es en danger immédiat\n\nTu N'ES PAS un fardeau. Les adultes veulent t'aider. Ta vie est importante.\n\nPeux-tu me dire : es-tu en sécurité maintenant ? Y a-t-il un adulte près de toi ?",
    },
    critical: {
      adult: "Je suis extrêmement inquiet pour votre sécurité immédiate. Ce que vous décrivez est une urgence, et vous méritez une aide et un soutien immédiats.\n\n**AGISSEZ MAINTENANT - Choisissez ce qui vous semble le plus réalisable :**\n\n• **Contactez** immédiatement un service d'aide en cas de crise - ils sont là pour vous aider\n• **Rendez-vous** aux urgences les plus proches\n• **Appelez** les services d'urgence (le 15 ou le 112) et précisez qu'il s'agit d'une urgence psychiatrique\n• **Contactez** une personne de confiance pour qu'elle soit avec vous en ce moment\n\nVotre douleur est réelle, mais la situation peut changer. Vous méritez de vivre et de vous sentir mieux que ça.\n\nJ'ai besoin de savoir : Êtes-vous en sécurité en ce moment ? Avez-vous fait quelque chose pour vous blesser ? Y a-t-il quelqu'un avec vous ?",
      minor: "Je m'inquiète énormément pour toi. C'est une urgence et tu as besoin d'aide TOUT DE SUITE.\n\n**FAIS ÇA IMMÉDIATEMENT :**\n\n• **PARLE** à un parent ou un adulte TOUT DE SUITE - montre-leur ce message\n• **CONTACTE** une ligne d'écoute - dis « J'ai besoin d'aide, je ne suis pas en sécurité »\n• **VA** aux urgences avec un adulte\n• **APPELLE** les services d'urgence - dis « J'ai besoin d'aide, c'est une urgence psychiatrique »\n\nTu n'es PAS seul(e). Tu n'es PAS un fardeau. Les adultes VEULENT t'aider. Ta vie est précieuse.\n\nS'il te plaît, dis-moi : Es-tu en sécurité maintenant ? T'es-tu blessé(e) ? Peux-tu aller voir un adulte ?",
    },
  },
  'ja': {
    none: {
      adult: "お話をお聞かせください。今日はどのようなことが心にありますか？",
      minor: "こんにちは。お話を聞きますよ。どんなことを話したいですか？",
    },
    low: {
      adult: "お気持ちを打ち明けてくださり、ありがとうございます。とても困難な状況にいらっしゃるのですね。そのようにお感じになるのは、ごく自然なことです。\n\nこうしてご連絡くださったことは、前向きな一歩です。もしよろしければ、カウンセラーやセラピストに相談することも、さらなるサポートになります。\n\n何が一番、心の重荷になっていますか？",
      minor: "打ち明けてくれてありがとうございます。とてもつらい状況なのですね。そう感じるのは、無理もないことですよ。\n\n勇気を出して話してくれたこと、本当にすごいと思います。時には、おうちの人やスクールカウンセラー、学校の先生など、信頼できる大人に話してみると、一人じゃないんだ、と感じられるようになることもありますよ。\n\nもし差し支えなければ、何があったのか、もう少し詳しく教えてもらえますか？",
    },
    medium: {
      adult: "あなたが今、どれほど辛い思いをされているか、伝わってきます。あなたのことを心から心配しています。そのお気持ちは、決して間違いではなく、とても大切なものです。\n\nあなたが安全でいられるように、力になりたいと思っています。安全を確保するために、次のような方法が役立つかもしれません。\n• 今日、話を聞いてもらったり、一緒にいてもらったりできる、信頼できる人に連絡してみる\n• すぐに助けを求められる、いのちの電話などの相談窓口に連絡する\n• 継続的なサポートのために、かかりつけ医やカウンセラーに相談する\n\nそのように感じていらっしゃるとのことですが、もしよろしければ、何があってそこまで追い詰められてしまったのか、お話しいただけますか？",
      minor: "あなたの状況をとても心配しています。あなたの気持ちはとても大切で、あなたはサポートを受けるに値する存在ですよ。\n\n今、ぜひやってほしい大切なことがあります。\n• 今日中に、信頼できる大人（親や保護者、先生、カウンセラーなど）に話すこと\n• 必要な時はいつでも、専門の相談窓口が利用できると知っておくこと\n• 適切な助けがあれば、今の気持ちは変わっていくものだと覚えておくこと\n\n一人じゃないよ。最近、どんなことが辛いと感じますか？",
    },
    high: {
      adult: "お話の内容を伺い、あなたのことがとても心配です。どんなに絶望的に感じられても、あなたはかけがえのない大切な存在だということを忘れないでください。\n\n以下の方法で、すぐにサポートを求めてください。\n• 危機相談ホットライン - 専門の相談員が24時間いつでも対応します\n• 地域の緊急通報サービス - 身の危険を感じる場合\n• 信頼できる友人や家族 - あなたのそばにいてくれる人\n\n一人で抱え込む必要はありません。今すぐ利用できる助けがあります。\n\n教えていただけますか。あなたは今、安全な場所にいますか？そばに誰か一緒にいてくれる人はいますか？",
      minor: "あなたのことが今、とても心配です。あなたが感じていることは深刻なことで、すぐに助けが必要です。そして、あなたには助けを受ける権利があります。\n\n**今すぐ**、この中のどれか一つを必ず実行してください：\n• 保護者や信頼できる大人に、私に話してくれたことを伝えてください\n• 危機対応の相談窓口に連絡してください。そこでは、毎日たくさんの若い人たちの相談に乗っています\n• もし自分の身が安全ではないと感じたら、信頼できる大人と一緒に救急外来に行ってください\n• 命の危険が差し迫っている場合は、緊急通報（警察は110番、消防・救急は119番）に電話してください\n\nあなたは**決して**迷惑な存在ではありません。大人たちはあなたの力になりたいと思っています。あなたの命はとても大切です。\n\n教えてください。あなたは今、安全な場所にいますか？ 近くに大人の人はいますか？",
    },
    critical: {
      adult: "あなたの身の安全が、今すぐにでも危険な状態にあることを、非常に懸念しています。お話しくださった内容は緊急事態であり、あなたはすぐに助けやサポートを受けるべき大切な存在です。\n\n**今すぐ行動してください - ご自身で最も可能だと感じられる方法を選んでください：**\n\n• **連絡する** - 危機対応の相談窓口にすぐに連絡してください。相談員があなたの連絡を待っています。\n• **行く** - 最寄りの救急外来に行ってください。\n• **電話する** - 緊急通報用電話番号（119番など）に電話し、精神的な緊急事態であることを伝えてください。\n• **頼る** - 信頼できる人に連絡し、今すぐそばにいてもらうよう頼んでください。\n\nあなたの痛みは本物です。でも、その状況は変えられます。あなたは生きるべき大切な存在であり、今よりもっと楽になっていいのです。\n\n確認させてください：今、安全な場所にいますか？ご自身を傷つけるようなことを何かしましたか？誰か一緒にいますか？",
      minor: "あなたのことが、とても心配です。これは緊急事態です。今すぐ、助けが必要です。\n\n**今すぐ、これをしてください：**\n\n• **伝える**：今すぐ、親か信頼できる大人に、このメッセージを見せてください。\n• **相談する**：こころの相談窓口に電話してください。「助けてください、安全な場所にいません」と伝えてください。\n• **行く**：大人と一緒に、救急外来に行ってください。\n• **電話する**：救急車を呼んでください。「助けてください、精神的な緊急事態です」と伝えてください。\n\nあなたは、ひとりじゃない。あなたは、誰かの重荷なんかじゃない。大人たちは、あなたの助けになりたいと思っています。あなたのいのちは、とても大切です。\n\n教えてください。今、安全な場所にいますか？ 自分を傷つけたりしていませんか？ 大人のところへ行けますか？",
    },
  },
  'ru': {
    none: {
      adult: "Я здесь, чтобы выслушать и поддержать вас. Что у вас на душе сегодня?",
      minor: "Привет! Я здесь, чтобы выслушать. О чём тебе хотелось бы поговорить?",
    },
    low: {
      adult: "Спасибо, что поделились этим со мной. Похоже, вы столкнулись с чем-то действительно сложным, и вполне понятно, что вы так себя чувствуете.\n\nВы делаете важный шаг, обращаясь за поддержкой. Если вы сочтёте это полезным, разговор с психологом или психотерапевтом может оказать дополнительную поддержку.\n\nЧто вас беспокоит больше всего?",
      minor: "Спасибо, что доверяешь мне. Похоже, тебе сейчас очень нелегко, и твои чувства абсолютно нормальны.\n\nОчень смело с твоей стороны говорить об этом. Иногда разговор со взрослым, которому доверяешь — например, с кем-то из родителей, школьным психологом или учителем, — помогает почувствовать себя не так одиноко.\n\nМожешь рассказать подробнее, что происходит?",
    },
    medium: {
      adult: "Я слышу, как вам сейчас больно, и искренне за вас переживаю. То, что вы чувствуете, — реально, и это важно.\n\nЯ хочу помочь вам быть в безопасности. Вот что может помочь:\n• Связаться с человеком, которому вы доверяете, чтобы поговорить с ним или побыть рядом сегодня\n• Позвонить на телефон доверия или в службу кризисной поддержки для немедленной помощи\n• Поговорить с врачом или психотерапевтом для получения постоянной поддержки\n\nВы упомянули о своих чувствах. Расскажите, пожалуйста, что происходило в последнее время и привело вас в это состояние?",
      minor: "Меня очень беспокоит то, через что ты проходишь. Твои чувства важны, и ты заслуживаешь поддержки.\n\nСейчас очень важно:\n• Поговорить сегодня со взрослым, которому ты доверяешь, — это может быть родитель, опекун, учитель или школьный психолог.\n• Знать, что кризисная помощь доступна в любое время, когда она тебе понадобится.\n• Помнить, что эти чувства могут пройти, если получить правильную помощь.\n\nТы в этом не один/одна. Расскажи, из-за чего тебе в последнее время так тяжело?",
    },
    high: {
      adult: "То, что вы описываете, меня очень беспокоит, и я хочу, чтобы вы знали, что ваша жизнь имеет ценность и смысл, даже когда кажется, что всё невозможно.\n\nПожалуйста, обратитесь за немедленной поддержкой:\n• Позвоните на телефон доверия — квалифицированные консультанты работают круглосуточно\n• Позвоните в местные экстренные службы, если вы чувствуете себя в опасности\n• Свяжитесь с другом или родственником, которому доверяете и который может побыть с вами\n\nВам не нужно проходить через это в одиночку. Помощь доступна прямо сейчас.\n\nСкажите, пожалуйста: вы в безопасном месте? Есть ли рядом кто-то, кто мог бы побыть с вами?",
      minor: "Я очень за тебя переживаю. То, что ты чувствуешь, — это серьёзно. Тебе нужна помощь, и ты заслуживаешь получить её немедленно.\n\nПожалуйста, сделай **ОДНО** из этого **ПРЯМО СЕЙЧАС**:\n• Расскажи родителю или взрослому, которому доверяешь, то, что ты только что мне рассказал(а).\n• Позвони на телефон доверия — они каждый день помогают подросткам.\n• Поезжай в отделение неотложной помощи со взрослым, которому доверяешь, если чувствуешь, что тебе небезопасно.\n• Позвони в экстренные службы, если ты в непосредственной опасности.\n\nТы **НЕ** обуза. Взрослые хотят тебе помочь. Твоя жизнь важна.\n\nСкажи, пожалуйста: ты сейчас в безопасности? Рядом есть кто-нибудь из взрослых?",
    },
    critical: {
      adult: "Я крайне обеспокоен вашей безопасностью в данный момент. То, что вы описываете, — это экстренная ситуация, и вы заслуживаете немедленной помощи и поддержки.\n\n**ДЕЙСТВУЙТЕ НЕМЕДЛЕННО. Выберите то, что вам сейчас по силам:**\n\n• **Свяжитесь** немедленно с телефоном доверия — там ждут, чтобы вам помочь\n• **Отправляйтесь** в ближайшее отделение неотложной помощи\n• **Позвоните** в экстренные службы и сообщите, что это экстренная ситуация, связанная с психическим здоровьем\n• **Обратитесь** к кому-то, кому вы доверяете, чтобы этот человек был сейчас рядом с вами\n\nВаша боль реальна, но всё может измениться. Вы заслуживаете жить и чувствовать себя лучше.\n\nМне нужно знать: вы сейчас в безопасности? Вы уже сделали что-нибудь, чтобы навредить себе? С вами кто-нибудь есть?",
      minor: "Я ужасно за тебя переживаю. Это экстренная ситуация, и тебе нужна помощь ПРЯМО СЕЙЧАС.\n\n**СДЕЛАЙ ЭТО НЕМЕДЛЕННО:**\n\n• **СКАЖИ** родителю или взрослому ПРЯМО СЕЙЧАС — покажи им это сообщение\n• **СВЯЖИСЬ** со службой кризисной помощи — скажи: «Мне нужна помощь, я не в безопасности»\n• **ОТПРАВЛЯЙСЯ** в отделение неотложной помощи со взрослым\n• **ПОЗВОНИ** в службу спасения — скажи: «Мне нужна помощь, у меня неотложное психологическое состояние»\n\nТы НЕ один/одна. Ты НЕ обуза. Взрослые ХОТЯТ тебе помочь. Твоя жизнь бесценна.\n\nПожалуйста, скажи мне: ты сейчас в безопасности? Ты причинил(а) себе вред? Ты можешь обратиться к взрослому?",
    },
  },
  'de': {
    none: {
      adult: "Ich bin hier, um dir zuzuhören und dich zu unterstützen. Was beschäftigt dich heute?",
      minor: "Hallo, ich bin hier, um dir zuzuhören. Worüber möchtest du sprechen?",
    },
    low: {
      adult: "Danke, dass du das mit mir teilst. Es klingt, als hättest du gerade mit etwas sehr Herausforderndem zu kämpfen, und es ist absolut verständlich, dass du dich so fühlst.\n\nEs ist ein positiver Schritt, dass du dich meldest. Falls es dir helfen würde: Ein Gespräch mit einem Berater oder Therapeuten kann zusätzliche Unterstützung bieten.\n\nWas belastet dich im Moment am meisten?",
      minor: "Danke, dass du mir das anvertraust. Was du durchmachst, klingt wirklich schwer, und deine Gefühle sind absolut verständlich.\n\nEs ist sehr mutig von dir, darüber zu sprechen. Manchmal hilft es, mit einer Vertrauensperson zu sprechen – zum Beispiel mit einem Elternteil, einem Vertrauenslehrer oder einer anderer Lehrkraft –, damit du dich weniger allein fühlst.\n\nMagst du mir mehr darüber erzählen, was los ist?",
    },
    medium: {
      adult: "Ich höre, wie sehr Sie gerade leiden, und ich mache mir aufrichtig Sorgen um Sie. Ihre Gefühle sind real und wichtig.\n\nIch möchte Ihnen helfen, sicher zu bleiben. Was Ihnen helfen könnte:\n• Wenden Sie sich an eine Person, der Sie vertrauen, mit der Sie heute sprechen oder zusammen sein können.\n• Kontaktieren Sie eine Krisenhotline für sofortige Hilfe.\n• Sprechen Sie mit Ihrem Arzt/Ihrer Ärztin oder einem Therapeuten/einer Therapeutin, um weiterführende Unterstützung zu erhalten.\n\nSie haben erwähnt, dass Sie sich so fühlen – können Sie mir erzählen, was passiert ist, das Sie an diesen Punkt gebracht hat?",
      minor: "Ich mache mir wirklich Sorgen um dich. Deine Gefühle sind wichtig und du verdienst Unterstützung.\n\nGerade jetzt ist es wirklich wichtig:\n• Sprich noch heute mit einem Erwachsenen, dem du vertraust – zum Beispiel mit einem Elternteil, einer Lehrkraft oder einer Beratungsperson.\n• Wisse, dass Krisenunterstützung jederzeit für dich da ist, wenn du sie brauchst.\n• Denk daran, dass sich diese Gefühle mit der richtigen Hilfe wieder ändern können.\n\nDu bist damit nicht allein. Was hat dir in letzter Zeit so zu schaffen gemacht?",
    },
    high: {
      adult: "Was Sie beschreiben, macht mir große Sorgen, und ich möchte, dass Sie wissen, dass Ihr Leben wertvoll ist und einen Sinn hat, auch wenn sich gerade alles unmöglich anfühlt.\n\nBitte holen Sie sich sofortige Unterstützung über:\n• Eine Krisen-Hotline – geschulte Beraterinnen und Berater sind rund um die Uhr erreichbar\n• Den örtlichen Rettungsdienst, wenn Sie sich nicht sicher fühlen\n• Einen vertrauten Freund, eine vertraute Freundin oder ein Familienmitglied, der/die bei Ihnen sein kann\n\nSie müssen das nicht alleine durchstehen. Hilfe ist sofort verfügbar.\n\nKönnen Sie mir sagen: Sind Sie an einem sicheren Ort? Gibt es jemanden, der bei Ihnen sein könnte?",
      minor: "Ich mache mir gerade große Sorgen um dich. Was du fühlst, ist ernst, und du brauchst und verdienst sofort Hilfe.\n\nBitte tu JETZT SOFORT EINES davon:\n• Sag einem Elternteil oder einem Erwachsenen, dem du vertraust, was du mir gerade erzählt hast.\n• Kontaktiere eine Krisenhotline – die helfen jeden Tag jungen Menschen wie dir.\n• Geh mit einem Erwachsenen, dem du vertraust, in eine Notaufnahme, wenn du dich nicht sicher fühlst.\n• Ruf den Notruf (112), wenn du in unmittelbarer Gefahr bist.\n\nDu bist KEINE Last. Erwachsene wollen dir helfen. Dein Leben ist wichtig.\n\nKannst du mir sagen: Bist du gerade in Sicherheit? Ist ein Erwachsener in deiner Nähe?",
    },
    critical: {
      adult: "Ich bin zutiefst besorgt um Ihre unmittelbare Sicherheit. Was Sie beschreiben, ist ein Notfall, und Sie verdienen sofortige Hilfe und Unterstützung.\\n\\n**HANDELN SIE JETZT – Wählen Sie, was für Sie am ehesten möglich ist:**\\n\\n• **Kontaktieren Sie** sofort eine Krisenhotline – die Mitarbeitenden dort warten darauf, Ihnen zu helfen.\\n• **Gehen Sie** in die nächste Notaufnahme.\\n• **Rufen Sie** den Notruf (112) an und sagen Sie, dass es sich um einen psychiatrischen Notfall handelt.\\n• **Bitten Sie** eine Person, der Sie vertrauen, jetzt bei Ihnen zu sein.\\n\\nIhr Schmerz ist real, aber das muss nicht so bleiben. Sie verdienen es, zu leben und dass es Ihnen besser geht.\\n\\nIch muss wissen: Sind Sie in diesem Moment in Sicherheit? Haben Sie sich selbst verletzt? Ist jemand bei Ihnen?",
      minor: "Ich mache mir extrem große Sorgen um dich. Das ist ein Notfall und du brauchst SOFORT Hilfe.\\n\\n**MACHE DAS SOFORT:**\\n\\n• **SAG** es SOFORT einem Elternteil oder einem anderen Erwachsenen – zeig ihnen diese Nachricht\\n• **KONTAKTIERE** eine Krisenhotline – sag: „Ich brauche Hilfe, ich bin nicht sicher\"\\n• **GEH** mit einem Erwachsenen in eine Notaufnahme\\n• **RUF** den Rettungsdienst (112) an – sag: „Ich brauche Hilfe, ich habe einen psychischen Notfall\"\\n\\nDu bist NICHT allein. Du bist KEINE Last. Erwachsene WOLLEN dir helfen. Dein Leben ist wertvoll.\\n\\nBitte sag mir: Bist du jetzt sicher? Hast du dich selbst verletzt? Kannst du zu einem Erwachsenen gehen?",
    },
  },
};

/**
 * Get safe response for risk level, age band, and language
 */
export function getMultilingualSafeResponse(
  risk_level: RiskLevel,
  age_band: 'adult' | 'minor' | 'unknown' = 'adult',
  language: string = 'en'
): string {
  const ageBand = age_band === 'minor' ? 'minor' : 'adult';
  
  // Extract language code from locale if needed (e.g., "en-US" -> "en")
  const langCode = language.split('-')[0].toLowerCase();
  
  // Check if we have translations for this language
  if (langCode in MULTILINGUAL_TEMPLATES) {
    return MULTILINGUAL_TEMPLATES[langCode as SupportedLanguage][risk_level][ageBand];
  }
  
  // Fallback to English
  return MULTILINGUAL_TEMPLATES['en'][risk_level][ageBand];
}
